### ISSUE TITLE
separate_arguments with single argument is mis-reported with E1120

### ISSUE THREAD

**Issue by Takishima** [cheshirekow/cmake_format#280] opened 2021-09-17 11:52 UTC
MRE:

```cmake
cmake_minimum_required(VERSION 3.0)

set(VAR "-f -a")

separate_arguments(VAR)
```

Expected:

    No warnings

Actual:
```
/tmp/CMakeLists.txt
===================
/tmp/CMakeLists.txt:05,19: [E1120] Missing required positional argument

Summary
=======
files scanned: 1
found lint:
       Error: 1
```

According to the official CMake documentation, this syntax is valid since at least CMake 3.0: https://cmake.org/cmake/help/v3.0/command/separate_arguments.html:

```
separate_arguments(VARIABLE)

Convert the value of VARIABLE to a semi-colon separated list. All spaces are replaced with ‘;’. 
This helps with generating command lines.
```

I am not familiar with this code base yet, so I cannot propose a fix at the moment, but if nobody can take care of it, I'll have a look at implementing and submitting a fix in the coming weeks.

The function that needs to be fixed is here: 
https://github.com/cheshirekow/cmake_format/blob/904c42da298f7fda932d9ac774517c20e2667fb8/cmakelang/parse/funs/miscellaneous.py#L389

**Comment by jtojnar** [comment] 2022-10-06 19:45
Duplicate of https://github.com/cheshirekow/cmake_format/issues/218

**Closed** 2023-02-08 20:13 UTC
