### ISSUE TITLE
Do not break links and URLs

### ISSUE THREAD

**Issue by okainov** [cheshirekow/cmake_format#195] opened 2020-04-27 09:44 UTC
Example cmake line (partial extract from my cmake)
```cmake
# alternatively could use Wix generator - https://cmake.org/cmake/help/latest/cpack_gen/wix.html#cpack_gen:CPack%20WiX%20Generator
```

Result of the reformat:
```cmake
# alternatively could use Wix generator - ht
# tps://cmake.org/cmake/help/latest/cpack_gen/wix.html#cpack_gen:CPack%20WiX%20G
# enerator allow user to specify the installation path
```

Please do not break URLs in the middle. Even if URL is longer than line length, it presumably should be kept as is and treated as "atomic".

**Comment by cheshirekow** [comment] 2020-04-27 17:47
Looks like a duplicate of #182. Please upgrade to the latest version and let me know if this remains an issue. When I run `0.6.10` on your example I get the following:

```
# alternatively could use Wix generator -
# https://cmake.org/cmake/help/latest/cpack_gen/wix.html#cpack_gen:CPack%20WiX%20Generator
```

Feel free to add a comment if you get something different after upgrading.

**Closed by cheshirekow** 2020-04-27 17:47 UTC

**Comment by okainov** [comment] 2020-04-27 20:14
Thanks, I was using 0.6.9. Now it works 👍
