### ISSUE TITLE
Question of understanding regarding always_wrap

### ISSUE THREAD

**Issue by Weeena** [cheshirekow/cmake_format#180] opened 2020-03-30 09:29 UTC
I have some `CMakeLists.txt` file with e.g.
```
cmake_minimum_required(VERSION 3.5)

option(CONFIG_OPT_WARNINGS_AS_ERROR "Use -Werror option for gcc" OFF)

set(SOURCES src/File1.cpp src/File2.cpp src/File3.cpp src/File4.cpp src/File5.cpp)
```

I would like it to be formatted in the following way:
```
cmake_minimum_required(VERSION 3.5)

option(CONFIG_OPT_WARNINGS_AS_ERROR "Use -Werror option for gcc" OFF)

set(SOURCES
    src/File1.cpp
    src/File2.cpp
    src/File3.cpp
    src/File4.cpp
    src/File5.cpp
    )
```

I assumed I can achieve this by using `always_wrap`. Hence, in my json options file for CMake-Format I put the line:
```
"always_wrap": ["set"],
```
However, the `set` list doesn't get wrapped. Rather, with my settings the file looks this:
```
cmake_minimum_required(VERSION 3.5)

option(CONFIG_OPT_WARNINGS_AS_ERROR "Use -Werror option for gcc" OFF)

set(SOURCES src/File1.cpp src/File2.cpp src/File3.cpp src/File4.cpp
            src/File5.cpp
    )
```

Is my expectation regarding `always_wrap` wrong? How can I achieve the desired formatting for my example?

For reference, I attach the entire json configuation file.
[CMakeFormatOptions.zip](https://github.com/cheshirekow/cmake_format/files/4401873/CMakeFormatOptions.zip)

**Comment by cheshirekow** [comment] 2020-04-08 18:31
Your expectation matches the intended behavior of `always_wrap`. It might be broken, I'll have a look.

**Comment by carlosgalvezp** [comment] 2020-05-25 13:17
Same problem here, "always_wrap" doesn't seem to do what it advertises.

**Comment by cheshirekow** [comment] 2020-05-25 23:41
@carlosgalvezp is your use case the same? e.g. you want to always wrap "set()"?

**Comment by carlosgalvezp** [comment] 2020-05-26 07:50
@cheshirekow In my case I want to wrap "add_compile_options".
Example:
```
add_compile_options(
    -Wall
    -Werror
)
```

**Comment by cheshirekow** [comment] 2020-06-08 18:53
Ok, due to changes in the parse structure, the specification for `always_wrap` accidentally became really obtuse. I think it still works (ish):

* @Weena: I think you want `BodyNode/set/ArgGroupNode/PargGroupNode` 
* @carlosgalvezp: I think you want `BodyNode/add_compile_options/ArgGroupNode/PargGroupNode`

But this will fail for any statements within an if()/else(). I've done a little work to simplify this, so in the next release you can (actually, you will need to) omit some parts:

* `set/PargGroupNode[1]`
* `add_compile_options/PargGroupNode[0]`

Which will work at any "body" level. I will close this issue when the change is pushed.

**Comment by Weeena** [comment] 2020-06-15 07:40
Excuse me if I'm a nuisance. You write that I want `BodyNode/set/ArgGroupNode/PargGroupNode`. I wonder how I can get it? Is it possible with the `CMakeFormatOptions.json` I have? Or would I need to dive into python (which I haven't done up to now, I just used python it as black-box). Or would I need to study some of your documentation?

**Closed** 2020-07-29 19:43 UTC
Labels: acknowledged, fix-in-flight

**Comment by dfaure-kdab** [comment] 2022-01-10 17:36
I, too, expected `always_wrap = ['target_link_libraries'] ` to always wrap this command, but it has no effect.
I get changes like this
```
-target_link_libraries( kcookiejar5
-   Qt5::DBus
-   KF5::I18n
-   KF5::WidgetsAddons
-)
+target_link_libraries(kcookiejar5 Qt5::DBus KF5::I18n KF5::WidgetsAddons)
```

So I googled around found this issue, and based on the latest comments I tried
`always_wrap = ['target_link_libraries/ArgGroupNode/PargGroupNodeBodyNode']`
and
`always_wrap = ['target_link_libraries/ArgGroupNode']`
but this makes no difference.

Using cmakelang-0.6.13 as installed by pip on Linux.
The full file is up at http://www.davidfaure.fr/2022/.cmake-format

Can you explain how always_wrap is supposed to be used? The question here wasn't actually answered, as far as I can see.

Thanks for your efforts on cmake_format !

**Comment by Weeena** [comment] 2022-01-11 06:38
I can confirm that for me my question was not actually answered: As a matter of fact, since i couldn't get `always_wrap` to run, i decided against cmake-format. I guess I would give it a second try if there would be a solution for this issue.

**Comment by geoffoxholm** [comment] 2022-01-11 13:25
I got it to work for me by adding `[0]` at the end (to index the first set of children, I guess?). I can't remember where I found this. Hope it helps:

```sh
always_wrap = ['target_link_libraries/PUBLIC/PargGroupNode[0]']
```

**Comment by louwers** [comment] 2023-09-24 10:01
@cheshirekow Can this be re-opened?
