### ISSUE TITLE
cmake format 0.4.2 Ignores Boolean Configuration Values

### ISSUE THREAD

**Issue by sanssecours** [cheshirekow/cmake_format#70] opened 2018-09-16 06:44 UTC
# Steps to Reproduce the Problem

1. Install `cmake-format`

   ```sh
   pip install cmake-format==0.4.2 pyyaml
   ```

2. Create a configuration file `.cmake-format.yaml` with the following content

   ```yaml
   separate_ctrl_name_with_space: True
   separate_fn_name_with_space: True
   ```

3. Create a file `CMakeLists.txt` with the following content

   ```cmake
   cmake_minimum_required (VERSION 3.0)
   ```

4. Format the file with `cmake-format`

   ```sh
   cmake-format CMakeLists.txt
   ```

# Expected Result

The last command should print the following output:

```cmake
cmake_minimum_required (VERSION 3.0)
```

.

# Actual Result

The command `cmake-format CMakeLists.txt` prints the following output:

```cmake
cmake_minimum_required(VERSION 3.0)
```

.

# Additional Information

The previous version of `cmake-format` (`0.4.1`) produced the correct output. The current version of `cmake-format` also produces the correct formatting, if we specify the configuration values via command-line options:

```sh
cmake-format --separate-ctrl-name-with-space true --separate-fn-name-with-space true CMakeLists.txt
```

.

# System Information

**OS:** macOS 10.13.6
**Python Version:** Python 3.7.0

**Comment by cheshirekow** [comment] 2018-09-16 20:12
One thing did change with config loading to fix a bug. I suspect that change is causing this issue. I will try to reproduce and hopefully it will be a quick fix.

**Comment by cheshirekow** [comment] 2018-09-16 22:53
oh I see... the problem is here: https://github.com/cheshirekow/cmake_format/commit/b1cfbd66b57cb41a31c616444c356b7bcab9b984#diff-b131a70ead6ea4c9cb8d8c4791a93890R260

I shouldn't have changed `default=None` to `default=value` because later logic uses `None` to determine whether or not a command line override is present. As a result, all config file booleans will be ignored. I'll publish a fix for this shortly.

**Closed** 2018-09-17 02:48 UTC
Labels: acknowledged, bug
