### ISSUE TITLE
config file not properly loaded if no extension

### ISSUE THREAD

**Issue by bergercookie** [cheshirekow/cmake_format#45] opened 2018-06-21 13:25 UTC
The following set of commands don't respect the tab-size:

```cmake
if(condition)
                   include_diredctories(...)
...
...
endif()
```

I expect that when I run cmake-format --tab-size 4 <file> that the directives inside the `if` are going to be indented at 4 spaces as shown below, but instead clang-format overrides it and formats it at 2 spaces anyway.

```cmake
if(condition)
    include_diredctories(...)
endif()
```

Any pointers on this?

**Comment by bergercookie** [comment] 2018-06-21 13:44
This was because the config file was not read correctly in the first place. It was named `.cmake_format` it was in python form (as the one in the main README.md for some reason it is not parsed at all at the end of `get_config` method. Renaming it to `.cmake_format.py` solved this.

In general I think the correct behavior would be for the algorithm to throw an exception if a configuration file was given in the command line but couldn't parse it correctly as in this case.

**Comment by cheshirekow** [comment] 2018-06-22 19:37
Actually `cmake_format` does throw an exception if you specify a configuration file that doesn't parse. Can you maybe describe your setup in a little more detail so I can try to replicate the issue?

**Comment by bergercookie** [comment] 2018-06-25 08:32
Take for example this configuration:

[cmake_format_example.tar.gz](https://github.com/cheshirekow/cmake_format/files/2132300/cmake_format_example.tar.gz)

Try running it with
cmake-format -c .cmake_format a.cmake

You'll see that the `include_directories` directive is indented at 2 spaces regardless of the value specified in the config file.

**Comment by cheshirekow** [comment] 2018-07-14 19:42
Thanks for the tarball. Indeed I see what you're reporting. `cmake-format -c .cmake_format --dump-config` prints `tab_size = 2` even thought the config file is `= 4`. 

The problem is https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/__main__.py#L155

```
      else:
        try_get_configdict(configfile_path)
```
should be
```
      else:
        config_dict = try_get_configdict(configfile_path)
```

Fix will be in next release.

**Closed** 2018-09-16 02:04 UTC
Labels: acknowledged, bug
